require('core.plugin_config.lualine')
require('core.plugin_config.nvim-tree')
require('core.plugin_config.swagger-preview')
require('core.plugin_config.bufferline')
require('core.plugin_config.treesitter')
require('core.plugin_config.zk-nvim')
-- require('core.plugin_config.telescope')
